# Generated by Django 3.2 on 2022-01-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_data', models.DateTimeField()),
                ('alarm_value', models.FloatField(max_length=200)),
                ('Text', models.CharField(max_length=500)),
                ('alarm_type', models.CharField(max_length=20)),
                ('Group', models.CharField(max_length=50)),
                ('priority', models.IntegerField(max_length=50)),
                ('Acked_data', models.DateTimeField()),
                ('Acked', models.BooleanField(default=False)),
            ],
        ),
    ]
