# Generated by Django 3.2 on 2022-01-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20220114_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Acked_data',
            field=models.DateTimeField(blank=True),
        ),
    ]
