# Generated by Django 3.2 on 2022-01-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_alter_person_acked_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Acked_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
