# Generated by Django 3.2 on 2022-01-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_alter_person_acked_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_data', models.DateTimeField(verbose_name='alarm data')),
                ('alarm_value', models.FloatField(verbose_name='alarm value')),
                ('Text', models.CharField(max_length=500, verbose_name='Text')),
                ('alarm_type', models.CharField(max_length=20, verbose_name='alarm type')),
                ('Group', models.CharField(max_length=50, verbose_name='Group')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('Acked_data', models.DateTimeField(blank=True, null=True, verbose_name='acked data')),
                ('Acked', models.BooleanField(default=False, verbose_name='acked')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='Acked',
            field=models.BooleanField(default=False, verbose_name='acked'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Acked_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acked data'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Group',
            field=models.CharField(max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Text',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='person',
            name='alarm_data',
            field=models.DateTimeField(verbose_name='alarm data'),
        ),
        migrations.AlterField(
            model_name='person',
            name='alarm_type',
            field=models.CharField(max_length=20, verbose_name='alarm type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='alarm_value',
            field=models.FloatField(verbose_name='alarm value'),
        ),
        migrations.AlterField(
            model_name='person',
            name='priority',
            field=models.IntegerField(verbose_name='priority'),
        ),
    ]
